version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    command: sh -c "npm start"

  server:
    build:
      context: ./server
    ports:
      - "3002:3002"
    command:
      sh -c "npm start"
