module.exports = {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_LIST_UPDATED: 'USER_LIST_UPDATED',

  USER_TYPING: 'USER_TYPING',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_LIST_UPDATED: 'MESSAGE_LIST_UPDATED',

  CHANGE_USERNAME: 'CHANGE_USERNAME'  
}
