module.exports = {
    START_APP: 'START_APP',

    UPDATE_USER_LIST: 'UPDATE_USER_LIST',

    SET_STATUS_TO_TYPING: 'SET_STATUS_TO_TYPING',
    SEND_MESSAGE: 'SEND_MESSAGE',
    UPDATE_MESSAGE_LIST: 'UPDATE_MESSAGE_LIST'
}
